### PR TITLE
fix: remove ZIP_AVAILABLE that avoiding package loading

### LINKED ISSUE #58: [Question] The menu item don't display
**Question**
IDK why is it happend. It works only 1 time. I want to using this package to manage nuget. So, I removed all nuget install by nugetforunity. Then, after recompile the menu item disappear. And I can't make it appear again. 
I tried install nugetforunity and this package. After restart, the menu item of nugetforunity appearing. But not this package.
I have no idea for how can I debug for this. So creating a question

### LINKED ISSUE #66: [BUG] `'Package' does not contain a definition for 'targetFramework'`
**Describe the bug**
Well. A bug
```
Library\PackageCache\org.kumas.nuget-importer@e006d74628\Editor\PackageOperation\OperatePackage.cs(251,112): error CS1061: 'Package' does not contain a definition for 'targetFramework' and no accessible extension method 'targetFramework' accepting a first argument of type 'Package' could be found (are you missing a using directive or an assembly reference?)
```

### LINKED ISSUE #67: Invalid operation should attach detail such as stacktrace or detailed message
**Is your feature request related to a problem? Please describe.**
Can't know the reason of a rollback. Just failed
The log to unity debug will be cleared after rollback that triggering reinstall packages

### LINKED ISSUE #69: [BUG] Won't prefer .net standard 2.1 when possible
**Describe the bug**
When the unity is able to target.net standard 2.1. The importer won't try to install
https://www.nuget.org/packages/Microsoft.Extensions.Logging/7.0.0

### PR DESCRIPTION
**Pull request by SettingDust**
fix #66 
fix #58 
fix #67 
fix #69

### CODE REVIEW

**Review by kumaS-nu — COMMENTED** [review]
`ZIP_AVAILABLE` is a flag that states that `csc.rsp` is set and can decompress Zip files. This package requires that the environment can unzip. So, if we remove `ZIP_AVAILABLE` from asmdef, users get a compile error when introducing this package. This makes it hard to install NuGet importer for Unity. 

The effect of this change is summarized below.
Advantages
- We can use this when starting with a compilation error

Disadvantages
- Compilation errors occur during the introduction

I prefer to keep `ZIP_AVAILABLE` in asmdef because opening a project with compile errors is less frequent than when introducing this.

Please give me any comments about this.

**Comment by SettingDust** [comment]
> I prefer to keep `ZIP_AVAILABLE` in asmdef because opening a project with compile errors is less frequent than when introducing this.

The problem is about half package I want to install from nuget is some package from upm need. 
In this situation, error will appear shows that the upm package need a dependency. So, I know I should install a nuget package with this importer. But I have to uninstall the upm package, install dependencies, reinstall the upm package.

> ZIP_AVAILABLE is a flag that states that csc.rsp is set and can decompress Zip files. This package requires that the environment can unzip. So, if we remove ZIP_AVAILABLE from asmdef, users get a compile error when introducing this package. This makes it hard to install NuGet importer for Unity.

I'm not quite sure what's it. I haven't saw it take an affect anywhere. It's seems that `ZIP_AVAILABLE` only import `System.IO.Compression.FileSystem` in `csc.rsp`

**Comment by kumaS-nu** [comment]
> The problem is about half package I want to install from nuget is some package from upm need.

I see, I understand the necessity.
I tried removing `ZIP_AVAILABLE` from asmdef and found it works differently for Unity2020 and Unity2021 or later. Unity2020 throws a compile error by this. Unity2021 or later works fine.

> It's seems that `ZIP_AVAILABLE` only import `System.IO.Compression.FileSystem` in `csc.rsp`

Yes, correct. This package uses `Compression.FileSystem`, which causes compile errors. I prevented the compile errors by only compiling when `ZIP_AVAILABLE` is defined.

Therefore, the current version of Unity does not need to avoid compiling by using `ZIP_AVAILABLE`. So let's remove `ZIP_AVAILABLE` from asmdef.
I will write a note about this in the documentation.

**Comment by kumaS-nu** [comment]
My GitHub Actions seem broken so I will ignore the test results.

I will check and fix it in my environment.
I will release it after I have some features that I want to add.

**Pull request merged**
